package com.zebra.ai.barcodefinder.domain.enums

enum class RepositoryState {
    NOT_INITIALIZED,
    BARCODE_DECODER_INITIALIZED,
    ENTITY_TRACKER_INITIALIZED,
    CAMERA_PERMISSION_REQUIRED,
    CAMERA_PERMISSION_RECEIVED,
    CAMERA_PERMISSION_DENIED,
    CAMERA_INITIALIZED,
    REPOSITORY_READY
}
